#!/bin/bash

echo "Files in plugins/example directory:"

# 读取目录中的文件，并为每个文件标上序号
files=(plugins/example/*)
num=1
for file in "${files[@]}"; do
    echo "$num. $(basename "$file")"
    ((num++))
done

# 提示用户输入要删除的文件的序号
echo "Enter the number(s) of file(s) you want to delete, separated by space:"
read -r line

# 定义一个函数，用于检查输入的序号是否合法
function check_num {
    local re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] || (( $1 < 1 || $1 > ${#files[@]} )); then
        echo "Invalid number: $1. Please enter a valid number between 1 and ${#files[@]}."
        exit 1
    fi
}

# 检查用户输入的序号是否合法
if [ -z "$line" ]; then
    echo "No input detected, please enter a valid input."
    exit 1
fi

IFS=' ' read -r -a nums <<< "$line"
for num in "${nums[@]}"; do
    check_num "$num"
done

# 确认用户是否要删除选中的文件
echo "Are you sure you want to delete these files? (Y/n)"
read -r confirmation

if [[ $confirmation =~ ^([yY]|[yY][eE][sS])$ ]]; then
    # 删除用户输入的指定文件
    for num in "${nums[@]}"; do
        file="${files[num-1]}"
        if [ -f "$file" ]; then
            rm -rf "$file"
            echo "File $(basename "$file") has been deleted."
        fi
    done
    # 输出删除成功信息
    echo "All selected files have been deleted."
else
    echo "Operation cancelled. Exiting..."
    exit 0
fi